version: 1
formatters:
  std:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: std
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: INFO
    formatter: std
    filename: "dolma/logs/pipeline_master.log"
loggers:
  DolmaDownloader:
    level: INFO
    handlers: [console, file]
    propagate: false
  DolmaExtractor:
    level: INFO
    handlers: [console, file]
    propagate: false
root:
  level: WARNING
  handlers: [console]
